### ISSUE TITLE
Issues with https

### ISSUE THREAD

**Issue by amalic** [mo-ld/mold-dock#3]
I have mo-ld running at https://mo-ld.org and I am experiencing some issues.  

- Use "//" instead of "http://" in main.js and html files (i fixed this, inside the running container)
- Fragments tries to access an entpoing at https://...80 (https != port 80)
- It starts now with the Query page instead of the About page
- The Mold network diagram on the About page does not show up any more

**Comment by zorino** [comment]
The use of "//" is valid and supported in all browsers and it inherits the protocol in place either http or https ....
See https://stackoverflow.com/questions/4659345/is-there-any-downside-for-using-a-leading-double-slash-to-inherit-the-protocol-i

Can you refer to some code for the fragments issue.

Changing all the // url with http force http over https ... and probably caused the error 

![image](https://user-images.githubusercontent.com/1028795/30117490-5a8d7b46-92ee-11e7-891c-96f77d8b6c5e.png)


https://prefix.cc/popular/all.file.json should be used

**Comment by amalic** [comment]
I changed it only in main.js and for the GetFlash page which is being displayed when Adobe Flash is not activated.

About the Fragments issue Firefox and Chrome seem to behave diffrently.

**Comment by amalic** [comment]
About the Fragments issue Firefox and Chrome seem to behave diffrently.

**Comment by amalic** [comment]
Any update on https support?

**Comment by zorino** [comment]
Like shown below the problem occurs because of yasqe.bundle.min.js calling a non https url -> http://prefix.cc/popular.all.file.json

It is indeed hardcoded and still there in the latest version of yasqe .. (https://github.com/OpenTriply/YASGUI.YASQE/blob/gh-pages/dist/yasqe.bundled.js).

Since https://prefix.cc/popular.all.file.json is valid, a quick fix could be to replace that in the script of mold-webapp.

But other problems of Mixed Content might still appear with other http URLs.

**Comment by zorino** [comment]
As for the services vt, ldf and the api, I've just committed a fix, can you try it.
See https://github.com/mo-ld/mold-webapp/blob/master/js/main.js

**Comment by amalic** [comment]
I agree, the mixed content problem can happen with other http urls. 

Replaced the main.js file directly inside the container. Looks good --> https://mo-ld.org/
Thanks for that!
